company_analytics:
  outputs:
    dev:
      account: "{{ env_var('SNOWFLAKE_ACCOUNT_IDENTIFIER') }}"
      database: FREE_COMPANY_DATASET_OUTPUTS
      password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
      role: accountadmin
      schema: public
      threads: 8
      type: snowflake
      user: "{{ env_var('SNOWFLAKE_USER') }}"
      warehouse: compute_wh
  target: dev