version: "3.9"

services:

  certbot:
    image: certbot/certbot
    container_name: certbot
    networks:
      - webnet
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: /bin/sh -c "trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot --deploy-hook 'docker-compose restart app'; sleep 12h & wait $${!}; done"

  backend:
    depends_on:
      - certbot
    container_name: backend
    build:
      context: ./backend
    restart: always
    ports:
      - 8000:8000
    env_file:
      - .env
    environment:
      PORT: 8000

  frontend:
    depends_on:
      - backend
    container_name: frontend
    build:
      context: ./frontend
    restart: always
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      ORIGIN: "http://localhost:3000"