version: "3.9"

services:

  backend:
    container_name: backend
    build:
      context: ./backend
    volumes:
      - type: bind
        source: $HOME/.metaflowconfig/config.json
        target: /root/.metaflowconfig/config.json
    restart: always
    ports:
      - 8000:8000
    env_file:
      - .env
    environment:
      PORT: 8000

  frontend:
    depends_on:
      - backend
    container_name: frontend
    build:
      context: ./frontend
    restart: always
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      ORIGIN: "http://localhost:3000"